apiVersion: v1
kind: Service
metadata:
  name: express-service
  labels:
    app: express
    environment: production
spec:
  type: ClusterIP  # ← Changed back from LoadBalancer to save $12/month
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: express