apiVersion: v1
kind: ServiceAccount
metadata:
  name: express-service-account
  labels:
    app: express
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: express-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
  resourceNames: ["express-config", "flyway-config", "flyway-migrations"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["postgres-secret"]
---
# Connect the service account to the role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: express-role-binding
subjects:
- kind: ServiceAccount
  name: express-service-account  # This service account...
roleRef:
  kind: Role
  name: express-role  # ...gets these permissions
  apiGroup: rbac.authorization.k8s.io