apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  labels:
    app: monitoring
data:
  ENABLE_METRICS: "true"
  LOG_LEVEL: "info"
  HEALTH_CHECK_INTERVAL: "30s"
  PERFORMANCE_MONITORING: "true"