apiVersion: v1
kind: Pod
metadata:
  name: hello-world-1
  labels:
    app: hello
spec:
  containers:
  - name: hello
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-2
  labels:
    app: hello  # Same label!
spec:
  containers:
  - name: hello
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-3
  labels:
    app: hello  # Same label!
spec:
  containers:
  - name: hello
    image: nginx
    ports:
    - containerPort: 80