apiVersion: v1
kind: Service
metadata:
  name: express-service
  labels:
    app: express
spec:
  selector:
    app: express
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
