apiVersion: v1
kind: Service
metadata:
  name: express-service
  labels:
    app: express
    environment: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: express
