apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      initContainers:
      - name: wait-for-postgres
        image: postgres:17-alpine
        command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5432 -U app_user -d discbaboons_db; do echo "Waiting for PostgreSQL..."; sleep 2; done; echo "PostgreSQL is ready!"']
      - name: flyway-migrate
        image: flyway/flyway:latest
        command: ["flyway", "migrate"]
        envFrom:
        - configMapRef:
            name: flyway-config
        - configMapRef:
            name: monitoring-config
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: migrations-volume
          mountPath: /flyway/sql
          readOnly: true
      containers:
      - name: express
        image: discbaboons-express:v6
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: express-config
        - configMapRef:
            name: monitoring-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: JWT_REFRESH_SECRET
        # Microsoft Graph API Environment Variables
        - name: GRAPH_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: GRAPH_TENANT_ID
        - name: GRAPH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: GRAPH_CLIENT_ID
        - name: GRAPH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: GRAPH_CLIENT_SECRET
        - name: GRAPH_USER_ID
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: GRAPH_USER_ID
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: migrations-volume
        configMap:
          name: flyway-migrations