apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:  # Kubernetes will base64 encode these
  POSTGRES_PASSWORD: "secure_password_123"
  POSTGRES_ROOT_PASSWORD: "root_password_456"
  DATABASE_URL: "postgresql://app_user:secure_password_123@postgres-service:5432/discbaboons_db"